config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }

  root 'welcome#index'
  

  get 'challenges' => 'challenges#index'
  get 'users/:id' => 'users#show'
  get 'challenges/new' => 'challenges#new' 
  post 'challenges' => 'challenges#create'
  get 'challenges/:id' => 'challenges#show'

  put 'challenges/:id/complete' => 'challenges#complete', as: 'complete'
  delete 'challenges/:id/destroy' => 'challenges#destroy', as: 'destroy'

  get 'challenges/:id/edit' => 'challenges#edit', as: 'challenge_edit' 
  patch '/challenges/:id' => 'challenges#update', as: 'challenge'

  get 'challenges/:id/confirm' => 'challenges#confirm', as: :confirm_challenge
  post "/challenges/:id/confirm" => 'challenges#buy', as: :buy_challenge

end

app/models/challenge.rb
class Challenge < ActiveRecord::Base 
	belongs_to :challenger, :class_name => "User"
	belongs_to :challengee, :class_name => "User"
	belongs_to :challenger_charity, :class_name => "Charity"
	belongs_to :challengee_charity, :class_name => "Charity"


	

end 

app/models/charity.rb
class Charity < ActiveRecord::Base 
	has_many :challenges 
end 

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :challenges 
	#has_attached_file :avatar
	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
	validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

	# has_many :initiated_challenges, source: :challenger_id
 #  	has_many :received_challenges, source: :challengee_id

 #  	def challenges
 #    	initiated_challenges + received_challenges
 #  	end


	after_create :welcome_email
	# after_create :daily_reminder_email

	 # private
	
	  def welcome_email
	    TheMailers.welcome_email(self).deliver_now
	  end

	  # def daily_reminder_email
	  #   TheMailers.daily_reminder_email.deliver_now #took a self. out of this
	  # end


	  # def self.daily_reminder_email
	  # 	TheMailers.daily_reminder_email(self).deliver_now
	  # end




end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 #before_action :authenticate_user!
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController  
	before_action :authenticate_user!
	def new 
		@charities = Charity.all.collect {|p| [ p.name, p.id ] }
		@users = User.all.collect {|p| [ p.username, p.id ] }
		@challenge = Challenge.new
	end 

	def create 
		@challenge = Challenge.create(challenge_params.merge(:challenger_id => current_user.id, :accepted => false, :current_day => 1, :start_date => Date.today, :completed => false, :challengee_task => false, :challenger_task => false, :challenger_funds => 0.00, :challengee_funds => 0.00))
		@challenge.update(:end_date => @challenge[:total_days].days.from_now)
		#@challenge.update(:end_date => @challenge[:total_days].days_from_now)
		redirect_to confirm_challenge_path(@challenge)
	end 

	def show 
		@challenge = Challenge.find(params[:id])
		# @day = UpdateWorker.perform(Challenge.find(params[:id]).current_day)
	end 

	def index
		@challenges = Challenge.all	
	end

	def edit
		@charities = Charity.all.collect {|p| [ p.name, p.id ] }
		@challenge = Challenge.find(params[:id])
	end 

	def update 
		#binding.pry
		@challenge = Challenge.find(params[:id])
		@challenge.update_attributes(params.require(:challenge).permit(:challengee_charity_id))
		@challenge.update_attributes(:accepted => true)
		#@challenge.update_attributes(params.require(:challengee_charity_id)) 
		redirect_to confirm_challenge_path(@challenge), notice: "Challenge Accepted!"
	end 

	def confirm
		@challenge = Challenge.find(params[:id])
	end

	def destroy
		@challenge = Challenge.find(params[:id])
		@challenge.destroy
		redirect_to "/users/#{current_user.id}", notice: "Challenge Declined" 
	end 

	
	def buy
	@challenge = Challenge.find(params[:id])
    @amount = (@challenge.total_days * 100) # placeholder

    customer = Stripe::Customer.create(
      :email => 'example@stripe.com',
      :card  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => "#{@challenge[:challenge_description]}",
      :currency    => 'usd'
    )

    redirect_to "/users/#{current_user.id}", notice: "Success! You are going to #{@challenge[:challenge_description]} for #{@challenge[:total_days]}"
  	rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to "/users/#{current_user.id}"
	end

	def complete 
		@challenge = Challenge.find(params[:id])
		if current_user.id == @challenge[:challenger_id]
			@challenge.update_attributes(:challenger_task => true)
			redirect_to "/users/#{current_user.id}", notice: "You completed your challenge today - Nice Work!"
		else 
			@challenge.update_attributes(:challengee_task => true)
			redirect_to "/users/#{current_user.id}", notice: "You completed your challenge today - Nice Work!"
		end 
	end 


	private

	def challenge_params 
		params.require(:challenge).permit(:challengee_id, :challenge_description, :total_days, :challenger_charity_id)
	end 

	


end

app/controllers/charities_controller.rb
class CharitiesController < ApplicationController 
end 

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController 

	private 

	def sign_up_params 
		params.require(:user).permit(:first_name, :last_name, :username, :email, :password, :password_confirmation, :avatar)
	end 

	def account_update_params 
		params.require(:user).permit(:first_name, :last_name, :username, :email, :password, :password_confirmation, :current_password, :avatar)
	end 

end 

app/controllers/users_controller.rb
class UsersController < ApplicationController 
	before_action :authenticate_user!
	def show 
		@user = User.find(params[:id]) 
		@active_challenges = []
		@pending_challenges = [] 
		@completed_challenges = []
		@challenges = Challenge.where(:challenger_id => @user.id) + Challenge.where(:challengee_id => @user.id)
		@challenges.each do |challenge| 
			if challenge[:complete]
				@completed_challenges << challenge 
			elsif !challenge[:accepted] 
				@pending_challenges << challenge 
			else 
				@active_challenges << challenge
			end 
		end 

	end 

	def new
		@user = User.new(sign_up_params)
	end

	def profile
    	redirect_to "users/#{current_user.id}"
  	end

  	# def 

	# def sign_up_params 
	# 	devise_parameter_sanitizer.sanitize(:sign_up)
	# end 




end 

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController 
	def index 
	end 
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_nav.html.erb
<nav class="navbar navbar-default" class="navbar-no-margin-bottom">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Charity Challenger</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->

      
      <ul class="nav navbar-nav navbar-right">
        <li><a>Signed in as <%=current_user[:username]%></a></li>
        <li><a href="/users/sign_out">Sign Out</a></li>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/application/_nav_not_signed_in.html.erb
<nav class="navbar navbar-default navbar-fixed-top" class="navbar-no-margin-bottom" class = "navbar-not-signed-in">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%=root_path%>">Charity Challenger</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    
      
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%=link_to 'Sign Up', new_user_registration_path%>
        </li>
        <li><a>Already Have An Account?</a></li>
        <li><%=link_to 'Sign In', new_user_session_path %></li>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/application/_nav_signed_in.html.erb
<nav class="navbar navbar-default navbar-fixed-top" class="navbar-no-margin-bottom" class = "navbar-signed-in">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%=root_path%>">Charity Challenger</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="<%="/users/#{current_user.id}"%>">My Profile<span class="sr-only">(current)</span></a></li>
        <li><a href="<%=edit_user_registration_path%>">Edit My Account</a></li>
        <li class="active"><a href="/challenges/new">Create A New Challenge<span class="sr-only">(current)</span></a></li>
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <li><a>Signed in as <%=current_user[:username]%></a></li>
        <li>
          <%=link_to 'Sign Out', destroy_user_session_path, :method => 'DELETE' %>
        </li>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/challenges/confirm.html.erb
<div id="header">

          <!-- Logo -->
            <h1><a href="index.html" id="logo">CharityChallenger <em></em></a></h1>

            <!-- <div style="font-family: 'Philosopher', sans-serif;"><font size = "84" color = "#37c0fb">CharityChallenger</font></div> -->

          <!-- Nav -->
            <nav id="nav">
              <ul>
                <% if user_signed_in? %>
                  
                  <li class="current"><a href=<%=root_path%>>Home</a></li>
                  <li><a href="<%="/users/#{current_user.id}"%>">My Profile</a></li>
                  <li><a href="<%=edit_user_registration_path%>">Edit Account</a></li>
                  <li><a href="/challenges/new">Create A New Challenge</a></li>
                  <li><a>Signed in as <%=current_user[:username]%></a></li>
                  <li><%=link_to 'Sign Out', destroy_user_session_path, :method => 'DELETE' %></li>
                <% else %>
                  <li><%=link_to 'Sign Up', new_user_registration_path%></li>
                      <li><a>Already Have An Account?</a></li>
                      <li><%=link_to 'Sign In', new_user_session_path %></li>
                <% end %>
              </ul>
            </nav>

        </div>
<div class='form'>
<div class="confirm">
<div class="container">
<br /><br />
<h7>Confirm Your Challenge!</h7><br /><br />


<p><%= image_tag User.find(@challenge[:challenger_id]).avatar.url(:medium), :class => 'avatar'%><h8> vs </h8><%= image_tag User.find(@challenge[:challengee_id]).avatar.url(:medium), :class => 'avatar'%><br />
<%=User.find(@challenge[:challenger_id]).username %> vs <%= User.find(@challenge[:challengee_id]).username %><br />

<br />
Challenge: <%=@challenge[:challenge_description]%><br />
<br />
My Charity: <% if current_user.id == @challenge[:challenger_id] %>
 <%= Charity.find(@challenge[:challenger_charity_id]).name %><br />
 <br />
  <% if @challenge[:challenger_charity_id].nil? %>
  <%= User.find(@challenge[:challengee_id])[:username]%> has not yet picked a challenge
  <%else%> 
  <%= User.find(@challenge[:challengee_id])[:username] %>'s Charity: <%= Charity.find(@challenge[:challenger_charity_id]).name %> 
  <%end%>
 <% else %> 
 <%= Charity.find(@challenge[:challengee_charity_id]).name %> <br />
 <br />
 <%= User.find(@challenge[:challenger_id])[:username] %>'s Charity: <%= Charity.find(@challenge[:challenger_charity_id]).name %>
 <%end%>
</p>
<p>
  
  <%= form_tag confirm_challenge_path(@challenge) do %>
    <article>
      <label class="amount">
        <span>Amount: $<%= number_with_precision @challenge.total_days, precision: 2 %></span>
      </label>
    </article>

    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key="<%= ENV['STRIPE_PUBLIC_KEY'] %>"
            data-description="<%= @challenge[:challenge_description]%>"
            data-amount="<%= (@challenge.total_days * 100).floor %>"></script>
  <% end %>
</p>

</div>
</div>

app/views/challenges/edit.html.erb
<div id="header">

					<!-- Logo -->
						<h1><a href="index.html" id="logo">CharityChallenger <em></em></a></h1>

						<!-- <div style="font-family: 'Philosopher', sans-serif;"><font size = "84" color = "#37c0fb">CharityChallenger</font></div> -->

					<!-- Nav -->
						<nav id="nav">
							<ul>
								<% if user_signed_in? %>
									
									<li class="current"><a href=<%=root_path%>>Home</a></li>
									<li><a href="<%="/users/#{current_user.id}"%>">My Profile</a></li>
									<li><a href="<%=edit_user_registration_path%>">Edit Account</a></li>
									<li><a href="/challenges/new">Create A New Challenge</a></li>
									<li><a>Signed in as <%=current_user[:username]%><a></li>
									<li><%=link_to 'Sign Out', destroy_user_session_path, :method => 'DELETE' %></li>
								<% else %>
									<li><%=link_to 'Sign Up', new_user_registration_path%></li>
        							<li><a>Already Have An Account?</a></li>
        							<li><%=link_to 'Sign In', new_user_session_path %></li>
								<% end %>
							</ul>
						</nav>

				</div>
<div class='form'>
<div class = "form-challenge">
<div class="container">
<br /><br />
<h7>Accept your Challenge:</h7><br /><br />



<p><%= image_tag User.find(@challenge[:challenger_id]).avatar.url(:medium), :class => 'avatar'%><h8> vs </h8> <%= image_tag User.find(@challenge[:challengee_id]).avatar.url(:medium), :class => 'avatar'%><br />
<%=User.find(@challenge[:challenger_id]).username %> vs <%= User.find(@challenge[:challengee_id]).username %><br />
<br />
Challenge: <%=@challenge[:challenge_description]%><br />
<br />
 <%= User.find(@challenge[:challenger_id])[:username] %>'s charity: <%= Charity.find(@challenge[:challenger_charity_id]).name %>
 <br />

</p>
 To accept this challenge, please pick another Charity!
 <br />
 <br />

 <%= form_for @challenge do |f| %>
  <%= f.select(:challengee_charity_id, @charities) %> <br />
  <br/>
  <%= f.submit %>
  <%end%>
 </div>
 </div>
 </div>

app/views/challenges/index.html.erb
<div class="container">
index For the win team



<div>

<% @challenges.each do |challenge| %>
	<%= challenge %>
<%end %> 
<%= link_to "My Profile", "/users/#{current_user.id}" %>
</div>

app/views/challenges/new.html.erb
<div id="header">

          <!-- Logo -->
            <h1><a href="index.html" id="logo">CharityChallenger <em></em></a></h1>

            <!-- <div style="font-family: 'Philosopher', sans-serif;"><font size = "84" color = "#37c0fb">CharityChallenger</font></div> -->

          <!-- Nav -->
            <nav id="nav">
              <ul>
                <% if user_signed_in? %>
                  
                  <li class="current"><a href=<%=root_path%>>Home</a></li>
                  <li><a href="<%="/users/#{current_user.id}"%>">My Profile</a></li>
                  <li><a href="<%=edit_user_registration_path%>">Edit Account</a></li>
                  <li><a href="/challenges/new">Create A New Challenge</a></li>
                  <li><a>Signed in as <%=current_user[:username]%></a></li>
                  <li><%=link_to 'Sign Out', destroy_user_session_path, :method => 'DELETE' %></li>
                <% else %>
                  <li><%=link_to 'Sign Up', new_user_registration_path%></li>
                      <li><a>Already Have An Account?</a></li>
                      <li><%=link_to 'Sign In', new_user_session_path %></li>
                <% end %>
              </ul>
            </nav>

        </div>
<div class = "form">
  <div class="container">
  <br/><br/>
    <h7>Create a New Challenge</h7>
  <br/><br/>

    <p>

<div class="container">

<%= form_for @challenge do |f| %>
	Pick a User to Challenge:

  <%= f.select( :challengee_id, @users) %> <br />
 <br />


  <%= f.label "Enter a challenge description:" %>
  <%= f.text_field :challenge_description %><br />


  <%= f.label "Number of days:" %>
  <%= f.text_field :total_days, id: "num-days-input" %><br />


  Pick a Charity:
  <%= f.select( :challenger_charity_id, @charities) %> <br />
  <br />

  
  <%= f.submit %>
   <% end %>

  

  </p>
</div>
</div>
</div>


  
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>


<head>
  <title>CharityChallenger</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- <link href='http://fonts.googleapis.com/css?family=Philosopher:400,700' rel='stylesheet' type='text/css'> -->
</head>

<body>

<%= yield %>



<div class="alert"><%= notice %></div>
<div class="notice"><%= alert %></div>
</body>


</html>

app/views/users/profile_stuff.html.erb
<div class='page'>
<div class="container" class="profile-container">
	<div class="user-welcome">
		<h4 class="profile-header">Welcome <%=@user.first_name %> <%=@user.last_name %>! <br /></h4> <br />

		<%= image_tag @user.avatar.url(:medium), :class => 'avatar'%>
		<br />
		<br />
	</div>
	<div class="username">
		<%=@user.username %><br />
	</div>

	<div class="challenge-link">
		<%= link_to "Create New Challenge", challenges_new_path %><br />
	</div>

	<div class="row">
    	<div class="col-sm-4" class="col-challenges">

			<h3>Active Challenges:</h3> 
			<% if @active_challenges.empty? %>You have no active challenges<br /> <%end%>
				<ol>
				<% @active_challenges.each do |challenge| #to do - accomodate for empty, display You have no challenges %>
				<li>
				<%= User.find(challenge.challenger_id).username %> ($<%=number_with_precision(challenge.challenger_funds, :precision => 2)%>) vs <%= User.find(challenge.challengee_id).username %> ($<%=number_with_precision(challenge.challenger_funds, :precision =>2)%>)<br /> Challenge: <%=challenge[:challenge_description]%> <br />Today is day <%=challenge[:current_day]%> of <%=challenge[:total_days]%><br />
					<%= link_to "View this Challenge", "/challenges/#{challenge.id}" %><br />
					<% if current_user.id == challenge[:challenger_id] && !challenge[:challenger_task] %>
					<%= link_to "I completed my challenge today!", complete_path(challenge), :method => "put" %>
					<% elsif current_user.id == challenge[:challengee_id] && !challenge[:challengee_task] %>
					<%= link_to "I completed my challenge today!", complete_path(challenge), :method => "put" %>
					<% else %> 
					You completed your challenge today - good work! 
					<% end %>
				</li>
			<%end%>
			</ol>
		</div>

		<div class="col-sm-4" class="col-challenges">
			<h3>Pending Challenges:</h3> 
			<% if @pending_challenges.empty? %>You have no pending challenges <br/><%end%>
			<ol>
			<% @pending_challenges.each do |challenge| %>
			<li>
			<%= User.find(challenge.challenger_id).username %> vs <%= User.find(challenge.challengee_id).username %><br />
			Challenge: <%=challenge[:challenge_description]%><br />
				<% if challenge[:challengee_id] == current_user.id %>
				<%= link_to "Accept this Challenge", "/challenges/#{challenge.id}/edit" %><br /> <%= link_to "Decline this challenge", destroy_path(challenge), :method => "delete" %>
				<% else %>
				Waiting for <%= User.find(challenge[:challengee_id]).username %> to accept
				<%end%>
			</li>
			<%end%>
			</ol>
		</div>

		<div class="col-sm-4" class="col-challenges">
		<h3>Completed Challenges:</h3> 
			<% if @completed_challenges.empty? %>You have no completed challenges <br /><%end%>
				<ol>
				<% @completed_challenges.each do |challenge| %>
				<li>
				<%= User.find(challenge.challenger_id).username %> vs <%= User.find(challenge.challengee_id).username %><br />
				</li>
			<%end%>
		</ol>
		</div>
	</div>
</div>
</div>

app/views/users/show.html.erb
<div id="header">

					<!-- Logo -->
						<h1><a href="index.html" id="logo">CharityChallenger <em></em></a></h1>

						<!-- <div style="font-family: 'Philosopher', sans-serif;"><font size = "84" color = "#37c0fb">CharityChallenger</font></div> -->

					<!-- Nav -->
						<nav id="nav">
							<ul>
								<% if user_signed_in? %>
									
									<li class="current"><a href=<%=root_path%>>Home</a></li>
									<li><a href="<%="/users/#{current_user.id}"%>">My Profile</a></li>
									<li><a href="<%=edit_user_registration_path%>">Edit Account</a></li>
									<li><a href="/challenges/new">Create A New Challenge</a></li>
									<li><a href ="#">Signed in as <%=current_user[:username]%></a></li>
									<li><%=link_to 'Sign Out', destroy_user_session_path, :method => 'DELETE' %></li>
								<% else %>
									<li><%=link_to 'Sign Up', new_user_registration_path%></li>
        							<li><a>Already Have An Account?</a></li>
        							<li><%=link_to 'Sign In', new_user_session_path %></li>
								<% end %>
							</ul>
						</nav>

				</div>
			<!-- Gigantic Heading -->
				<section class="wrapper style2">
					<div class="container">
						<header class="major">
							<h2>Welcome <%=@user[:first_name]%> <%=@user[:last_name]%></h2>
							<p><%=@user[:username]%></p>
							<%= image_tag @user.avatar.url(:medium), :class => 'avatar'%>
						</header>
					</div>
				</section>

<section class="wrapper style">
					<div class="profilecontainer">
						<div class="row 200%">
							<section class="4u 12u(narrower)">
								<div class="box highlight">
									
									<h3>Pending Challenges</h3>
									<p>
									<% if @pending_challenges.empty? %>You have no pending challenges <br/><%end%>
									<ol>
									<% @pending_challenges.each do |challenge| %>
									<li>
									<%= User.find(challenge.challenger_id).username %> vs <%= User.find(challenge.challengee_id).username %><br />
									Challenge: <%=challenge[:challenge_description]%><br />
										<% if challenge[:challengee_id] == current_user.id %>
										<%= button_to "Accept this Challenge", challenge_edit_path(challenge), :method => 'get'%><br /> <%= button_to "Decline this challenge", destroy_path(challenge), :method => "delete" %>
										<% else %>
										Waiting for <%= User.find(challenge[:challengee_id]).username %> to accept
										<%end%>
									</li>
									<%end%>
									</ol></p>
									
								</div>
							</section>
							<section class="4u 12u(narrower)">
								<div class="box highlight">
									
									<h3>Active Challenges</h3>
									<p><% if @active_challenges.empty? %>You have no active challenges<br /> <%end%>
										<ol>
										<% @active_challenges.each do |challenge| #to do - accomodate for empty, display You have no challenges %>
										<li>
										<a href ="<%="/challenges/#{challenge.id}"%>"><%= User.find(challenge.challenger_id).username %> ($<%=number_with_precision(challenge.challenger_funds, :precision => 2)%>) vs <%= User.find(challenge.challengee_id).username %> ($<%=number_with_precision(challenge.challengee_funds, :precision =>2)%>)</a><br /> Challenge: <%=challenge[:challenge_description]%> <br />Today is day <%=challenge[:current_day]%> of <%=challenge[:total_days]%><br />
								
											<% if current_user.id == challenge[:challenger_id] && !challenge[:challenger_task] %>
											<%= button_to "I completed my challenge today!", complete_path(challenge), :method => "put" %>
											<% elsif current_user.id == challenge[:challengee_id] && !challenge[:challengee_task] %>
											<%= button_to "I completed my challenge today!", complete_path(challenge), :method => "put" %>
											<% else %> 
											Daily challenge completed - <br />good work! 
											<% end %>
										</li><br />
									<%end%>
									</ol></p>
								</div>
							</section>
							<section class="4u 12u(narrower)">
								<div class="box highlight">
									
									<h3>Completed Challenges</h3>
									<p><% if @completed_challenges.empty? %>You have no completed challenges <br /><%end%>
										<ol>
										<% @completed_challenges.each do |challenge| %>
										<li>
										<%= User.find(challenge.challenger_id).username %> vs <%= User.find(challenge.challengee_id).username %><br />
										</li>
									<%end%>
								</ol></p>
								</div>
							</section>
						</div>
					</div>
				</section>